return {
	bullet=
	{
		[1]=
		{
			id = 1,
			speed = 6,
			bullet_num = 1,
			bullet_prefab_name = "BulletPrefab1",
			move = "LineMove",
			hit_start = "IsHitSomeOne",
			hit_effect = "SampleHit",
			hit_type = "SectorShoot",
			bullet_life_time = 6,
		},
		[2]=
		{
			id = 2,
			speed = 4,
			bullet_num = 3,
			bullet_prefab_name = "BulletPrefab8",
			move = "LineMove",
			hit_start = "IsHitSomeOne",
			hit_effect = "SampleHit",
			hit_type = "SectorShoot",
			bullet_life_time = 6,
		},
		[3]=
		{
			id = 3,
			speed = 4,
			bullet_num = 1,
			shouji_pre = "gw_she_zidan_shouji",
			bullet_prefab_name = "BulletPrefab9",
			move = "LineMove",
			hit_start = "IsHitSomeOne",
			hit_effect = "SampleHit",
			hit_type = "SectorShoot#160",
			bullet_life_time = 6,
		},
		[4]=
		{
			id = 4,
			speed = 6,
			bullet_num = 1,
			bullet_prefab_name = "BulletPrefab12",
			move = "LineMove",
			hit_start = "IsHitSomeOne",
			hit_effect = "SampleHit",
			hit_type = "SectorShoot",
			bullet_life_time = 6,
		},
		[5]=
		{
			id = 5,
			speed = 6,
			bullet_num = 1,
			bullet_prefab_name = "BulletPrefab12",
			move = "LineMove",
			hit_start = "IsHitSomeOne",
			hit_effect = "SampleHit",
			hit_type = "SectorShoot",
			bullet_life_time = 6,
		},
		[6]=
		{
			id = 6,
			speed = 10,
			bullet_num = 1,
			bullet_prefab_name = "dufenhua_dufen",
			move = "BossWaveMove",
			hit_start = "IsHitSome",
			hit_effect = "ExtraPenetrateHit",
			hit_type = "SectorShoot",
			bullet_life_time = 2,
			attr = "Poisoning#10",
		},
		[7]=
		{
			id = 7,
			speed = 10,
			bullet_num = 1,
			shouji_pre = "GW_srh_baoza",
			bullet_prefab_name = "GW_srh_zidan",
			move = "DropGrenades",
			hit_start = "IsReachTarget",
			hit_effect = "BombHit#3",
			hit_type = "SectorShoot",
			bullet_life_time = 4,
			attr = "Poisoning#5",
		},
		[8]=
		{
			id = 8,
			speed = 10,
			bullet_num = 3,
			audio_name = "boss_attack3",
			shouji_pre = "BOOS_shouji_H",
			bullet_prefab_name = "BulletPrefab_boss1",
			move = "LineMove",
			hit_start = "IsHitSomeOne",
			hit_effect = "SampleHit",
			hit_type = "SectorShoot",
			bullet_life_time = 6,
		},
		[9]=
		{
			id = 9,
			speed = 10,
			bullet_num = 1,
			audio_name = "boss_attack1",
			bullet_prefab_name = "BOOS_Xrz_kuosan",
			move = "BossWaveMove",
			hit_start = "IsGQHitSomeOne",
			hit_effect = "PenetrateHit",
			hit_type = "GQShoot",
			bullet_life_time = 2,
		},
		[10]=
		{
			id = 10,
			speed = 20,
			bullet_num = 1,
			audio_name = "boss_attack2",
			shouji_pre = "BOOS_shouji_H",
			bullet_prefab_name = "BulletPrefab_boss1",
			move = "LineMove",
			hit_start = "IsHitSomeOne",
			hit_effect = "SampleHit",
			hit_type = "SectorShoot",
			bullet_life_time = 6,
		},
		[11]=
		{
			id = 11,
			speed = 10,
			bullet_num = 3,
			audio_name = "boss_attack3",
			shouji_pre = "BOOS_shouji_H",
			bullet_prefab_name = "BulletCrabBoss",
			move = "LineMove",
			hit_start = "IsHitSomeOne",
			hit_effect = "SampleHit",
			hit_type = "SectorShoot",
			bullet_life_time = 6,
		},
		[12]=
		{
			id = 12,
			speed = 10,
			bullet_num = 3,
			audio_name = "boss_attack3",
			bullet_prefab_name = "BOOS_liusha_zadi",
			move = "BossWaveMove",
			hit_start = "HitOnSelfPos",
			hit_effect = "PenetrateBombHit",
			hit_type = "SectorShoot",
			bullet_life_time = 0.800000,
		},
		[13]=
		{
			id = 13,
			bullet_num = 1,
			audio_name = "boss_attack1",
			bullet_prefab_name = "BOOS_skill_xuanwo",
			move = "BossWaveMove",
			hit_start = "IsHitSome",
			hit_effect = "ExtraPenetrateHit",
			hit_type = "SectorShoot",
			bullet_life_time = 10,
			attr = "Slow#50#0.2",
		},
		[14]=
		{
			id = 14,
			speed = 20,
			bullet_num = 20,
			audio_name = "boss_attack2",
			shouji_pre = "BOOS_shouji_H",
			bullet_prefab_name = "BulletCrabBoss",
			move = "LineMove",
			hit_start = "IsHitPlane",
			hit_effect = "RocketBombHit",
			hit_type = "SkillCrabRollDownShoot",
			bullet_life_time = 6,
		},
		[15]=
		{
			id = 15,
			speed = 5,
			bullet_num = 1,
			audio_name = "boss_attack3",
			shouji_pre = "xx_shouji",
			bullet_prefab_name = "BulletPrefab_duhua_super",
			move = "GQMoveWithSelf",
			hit_start = "IsHitSome",
			hit_effect = "ExtraPenetrateHit",
			hit_type = "SectorShoot",
			bullet_life_time = 99999,
			attr = "Poisoning#100",
		},
		[16]=
		{
			id = 16,
			speed = 10,
			bullet_num = 1,
			audio_name = "boss_attack1",
			bullet_prefab_name = "BulletPrefab_duhua_super",
			move = "BossWaveMove",
			hit_start = "IsHitSome",
			hit_effect = "ExtraPenetrateHit",
			hit_type = "SectorShoot",
			bullet_life_time = 10,
			attr = "Poisoning#100",
		},
		[17]=
		{
			id = 17,
			speed = 20,
			bullet_num = 1,
			audio_name = "boss_attack1",
			bullet_prefab_name = "jg_she_hongse",
			move = "LineCrossMove",
			hit_start = "HitLineCross",
			hit_effect = "ExtraPenetrateHit",
			hit_type = "SectorShoot",
			bullet_life_time = 0.500000,
			attr = "Poisoning#100",
		},
		[18]=
		{
			id = 18,
			speed = {6,3},
			bullet_num = {1,10},
			audio_name = "boss_attack3",
			shouji_pre = "BOOS_shouji_H",
			bullet_prefab_name = {"YX_zidna_huo_1","YX_zidna_huo_2"},
			move = {"LineMove","LineMove"},
			hit_start = {"IsHitSomeOneOrIsReachTarget","IsHitSomeOne"},
			hit_effect = {"SnakeSampleHit","SampleHit"},
			hit_type = {"SectorShoot","CircleShoot"},
			bullet_life_time = 30,
		},
		[19]=
		{
			id = 19,
			speed = 10,
			bullet_num = 20,
			shouji_pre = "BOOS_shouji_H",
			bullet_prefab_name = "YX_zidna_huo_2",
			move = "LineMove",
			hit_start = "IsHitSomeOne",
			hit_effect = "SampleHit",
			hit_type = "CircleShoot",
			bullet_life_time = 30,
		},
		[20]=
		{
			id = 20,
			speed = 40,
			bullet_num = 1,
			shouji_pre = "BOOS_shouji_H",
			bullet_prefab_name = "BulletPrefab_shandian_1",
			move = "LaserMoveRacastHit",
			hit_start = "IsRayCastLaserLock",
			hit_effect = "LaserHit",
			hit_type = "SectorShoot",
			bullet_life_time = 3,
		},
		[21]=
		{
			id = 21,
			speed = 6,
			bullet_num = 3,
			shouji_pre = "gw_she_zidan_shouji",
			bullet_prefab_name = "BulletPrefab9",
			move = "LineMove",
			hit_start = "IsHitSomeOne",
			hit_effect = "SampleHit",
			hit_type = "SectorShoot#160",
			bullet_life_time = 6,
		},
		[22]=
		{
			id = 22,
			speed = {6,0},
			bullet_num = {1,1},
			shouji_pre = {"nil","gw_zidan_px_shouji"},
			bullet_prefab_name = {"gw_zidan_Px","gw_zidan_Px"},
			move = {"DropGrenadesNoRotate","DontMove"},
			hit_start = {"IsReachTarget","TimeOver#3"},
			hit_effect = {"BombHit#1","BombHit#5"},
			hit_type = {"SectorShoot","SectorShoot"},
			bullet_life_time = 4,
		},
		[23]=
		{
			id = 23,
			speed = 25,
			bullet_num = 1,
			audio_name = "boss_attack3",
			shouji_pre = "BOOS_shouji_H",
			bullet_prefab_name = "BulletPrefab_ShouLiJian",
			move = "ReflectMove3",
			hit_start = "IsHitSomeOne",
			hit_effect = "SampleHit",
			hit_type = "SectorShoot",
			bullet_life_time = 2,
		},
	},
}